package askingAgent

import (
	"fmt"
	"github.com/katayunak/testigo/internal/askingAgent/askEntity"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// Written records what landed on disk and what the compiler thought of it.
type Written struct {
	Path     string
	Compiles bool
	Vets     bool
	Output   string
}

// generatedHeader marks the file so nobody mistakes it for hand-written code,
// and so testigo can find its own output again to replace or remove it.
const generatedHeader = `// Code generated by testigo (phase 2, AskingTheAgent). DO NOT EDIT BY HAND.
//
// This file was written by an agent from a prompt, then compiled and run
// automatically. It has not been reviewed by a person. Read it before you trust
// a green result from it: a generated test that asserts the wrong thing passes
// just as quietly as one that asserts the right thing.
//
// To regenerate:  testigo ask --round 2 && testigo collect
// To remove:      delete this file; nothing else references it.

`

// WriteTest puts the generated file in the package and asks the Go toolchain
// whether it is real.
//
// The toolchain is the referee, and it is the reason this whole approach is
// worth attempting in Go rather than a dynamic language. `go build` and `go vet`
// are fast, strict, and completely trustworthy — they cannot be talked into
// approving code that does not compile. Everything an agent produces gets
// checked by something that has no opinion about how hard it tried.
func WriteTest(root string, t *askEntity.CaseAnswer) (*Written, error) {
	if strings.TrimSpace(t.File.Content) == "" {
		return nil, fmt.Errorf("nothing to write: file.content is empty")
	}
	rel := filepath.Clean(t.File.Path)
	if filepath.IsAbs(rel) || strings.HasPrefix(rel, "..") {
		return nil, fmt.Errorf("refusing to write outside the repository: %q", t.File.Path)
	}
	if !strings.HasSuffix(rel, "_test.go") {
		return nil, fmt.Errorf("refusing to write %q: generated files must end in _test.go so they cannot ship in a binary", rel)
	}

	full := filepath.Join(root, rel)
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		return nil, err
	}
	content := t.File.Content
	if !strings.HasPrefix(content, "// Code generated by testigo") {
		content = generatedHeader + content
	}
	if err := os.WriteFile(full, []byte(content), 0o644); err != nil {
		return nil, err
	}

	w := &Written{Path: rel}
	pkgDir := "./" + filepath.ToSlash(filepath.Dir(rel)) + "/"

	var log strings.Builder
	if out, err := run(root, "go", "build", pkgDir); err != nil {
		fmt.Fprintf(&log, "go build failed:\n%s\n", out)
		w.Output = log.String()
		return w, nil
	}
	w.Compiles = true

	if out, err := run(root, "go", "vet", pkgDir); err != nil {
		fmt.Fprintf(&log, "go vet failed:\n%s\n", out)
		w.Output = log.String()
		return w, nil
	}
	w.Vets = true
	w.Output = log.String()
	return w, nil
}

// RunTests executes only the generated tests, with the race detector on.
//
// -race is not optional here. Two of the four idempotency properties are about
// concurrent requests, and a data race in the code under test makes any result
// from those meaningless — green because the race happened to go the right way
// this time.
func RunTests(root, rel string, names []string) (string, bool) {
	if len(names) == 0 {
		return "no tests to run", true
	}
	pkgDir := "./" + filepath.ToSlash(filepath.Dir(rel)) + "/"
	pattern := "^(" + strings.Join(names, "|") + ")$"
	out, err := run(root, "go", "test", "-race", "-count=1", "-run", pattern, pkgDir)
	return out, err == nil
}

func run(dir, name string, args ...string) (string, error) {
	cmd := exec.Command(name, args...)
	cmd.Dir = dir
	// GOWORK=off for the same reason the scanner sets it: an unrelated
	// workspace file above the target repository silently changes what builds.
	cmd.Env = append(os.Environ(), "GOWORK=off")
	out, err := cmd.CombinedOutput()
	return string(out), err
}
