package scanningFlow

import (
	"go/ast"
	"regexp"

	"golang.org/x/tools/go/packages"
)

// generatedMarker is the line Go tools agree on for machine-written files.
//
// The convention is fixed and documented at https://go.dev/s/generatedcode:
// the line must match exactly, and it must appear before the package clause.
// protoc, protoc-gen-go, grpc-gateway, mockgen, stringer and sqlc all emit it.
var generatedMarker = regexp.MustCompile(`^// Code generated .* DO NOT EDIT\.$`)

// generatedFiles returns the repo-relative paths of every generated file.
//
// Why testigo cares. A finding is a request that a person change something, and
// nobody changes a .pb.gw.go by hand — they change the .proto and regenerate.
// Reporting on generated code is therefore not a small amount of extra noise,
// it is noise that can never be actioned, and it arrives in bulk: on a real
// gRPC service 36% of the findings and six of the ten "state machines" came
// from api/pb, including an enum called SchedulingType that phase 2 would have
// paid an agent to describe the legal transitions of.
//
// Generated files stay in the call graph and keep their seams. The flow really
// does pass through them, and hiding that would make the map wrong. What they
// lose is the right to raise findings and to contribute patterns — the two
// things that ask a person for their attention.
func generatedFiles(pkgs []*packages.Package, root string) map[string]bool {
	out := map[string]bool{}
	for _, p := range pkgs {
		for _, f := range p.Syntax {
			if !isGenerated(f) {
				continue
			}
			if rel := relPath(p.Fset, f.Pos(), root); rel != "" {
				out[rel] = true
			}
		}
	}
	return out
}

// isGenerated reports whether a parsed file carries the marker in the only
// position that counts: above the package clause.
//
// The position matters. A comment further down saying "code generated by hand"
// is prose, not a declaration, and treating it as one would silence a file
// somebody does maintain.
func isGenerated(f *ast.File) bool {
	for _, group := range f.Comments {
		if group.Pos() > f.Package {
			break // past the package clause; everything after is ordinary comment
		}
		for _, c := range group.List {
			if generatedMarker.MatchString(c.Text) {
				return true
			}
		}
	}
	return false
}

// withoutGenerated drops the findings that point into machine-written files.
//
// It returns the count as well as the list, because a filter that hides its own
// work reads as "there was nothing there". The scan prints the number.
func withoutGenerated[T any](items []T, gen map[string]bool, fileOf func(T) string) ([]T, int) {
	if len(gen) == 0 {
		return items, 0
	}
	kept := make([]T, 0, len(items))
	dropped := 0
	for _, it := range items {
		if gen[fileOf(it)] {
			dropped++
			continue
		}
		kept = append(kept, it)
	}
	return kept, dropped
}
